### ISSUE TITLE
listener function for opcode 4 of wl_output is NULL

### ISSUE THREAD

**Issue by MultisampledNight** [r-c-f/waynergy#28]
On my second and every following execution of waynergy, this message is written out at start, quickly followed by a `SIGABRT`:

```
listener function for opcode 4 of wl_output is NULL
```

Since I don't know how to debug this, I can't really give environmental information except that I'm running on Arch Linux with sway. Installation was through a git clone and the procedure listed in `README.md` (letting out the `ninja install` part since I don't want to have waynergy in a global stance yet).

Additionally to some very... "generic" seeming stuff in the output like copyright information and somehow a child exit with a non-zero status, right the first line of terminal output is this one, even with `--backend wlr`:

```
uinput fd open failed: Permission denied
```

But that may or may not be related. I'd welcome any assistance or where I should search for state files of waynergy.

**Comment by r-c-f** [comment]
Thank you for reporting this, as it will no doubt affect many others. The abort issue was due to protocol version ambiguity which is now resolved on my end at least. Does the new release work for you? 

Also the uinput error should probably be clarified as normal for users of other backends. Because uinput is restricted, the idea is to allow for waynergy to be suid/sgid. It will immediately try to open the uinput device on launch, drop privileges permanently, and only then proceed to process any user configuration. This minimizes the potential attack surface for someone seeking privilege escalation.

**Comment by MultisampledNight** [comment]
That's sensible, I just tried it out, it runs and I can even move the mouse back and forth  (before crashing with a segmentation fault, but that's for another issue). I appreciate the time you put in this project.
