### ISSUE TITLE
[Question] Any plans for server support?

### ISSUE THREAD

**Issue by dmayle** [r-c-f/waynergy#57]
Hi,

I found this when wanting to connect my laptop to my desktop (the desktop is still running X), and it works wonderfully.  I would love to switch my desktop over to wayland as well, but barrier/synergy/input-leap don't support it.

Do you have any plans to add server support to waynergy?  I'd love to ditch X and switch over to waynergy only.

P.S. Thanks for developing a great tool!

**Comment by r-c-f** [comment]
It's almost certainly never going to happen simply because at that point an upstream barrier/synergy/input-leap contribution would make more sense. This project only started because -- at the time -- the upstream focus was on libei as an eventually unified solution and progress was being made; I've been reconsidering as this seems increasingly unlikely.

Aside from that, the technical challenge of actually capturing input successfully for a Wayland session is unlikely to be surmountable with anything approaching sanity, and my server setup can't run Wayland at all so motivation is a naturally a bit low.  For your immediate situation, I'd consider https://github.com/htrefil/rkvm

**Comment by dmayle** [comment]
Thank you, I'll give it a try.
