### ISSUE TITLE
GTK Application Menus

### ISSUE THREAD

**Issue by Reireiyan** [r-c-f/waynergy#68]
I'm on KDE, and I noticed GTK application menus do not work whenever I'm using the shared mouse with Waynergy; they are not clickable by mouse at all unless I hover over what I want to click in the menus then press the enter key on the keyboard instead to get things clicked in the menus.

**Comment by r-c-f** [comment]
This is a KWin bug: button events generated by the fake input protocol all had a time of 0, and (from a cursory glance at the gtk3 source) menu activation logic is very much time-sensitive. Coincidentally it was just fixed with https://github.com/KDE/kwin/commit/1a8c79653632c015cfb5e1831fcab0fde7eeca0e so there's not much to do here other than wait for it to be released, as the protocol provides no means to force a more sensible time value. 

Using the uinput waynergy backend is a possible workaround until then.
